### ISSUE TITLE
badge count in tabbar ? 

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/twitter-clone-with-graphql-reactnative#28]
Hi, Can you do this please ? Notification count in the react navigation tab bar icons. Obviously this will be a subscription. Hooking it with the  react navigation tab bar icons is the key. 

<img width="335" alt="badge" src="https://user-images.githubusercontent.com/5293742/30215904-36ee80b8-94d3-11e7-8524-f55f74de5e6f.png">

Or pointing me to the right direction will be huge help as well. Thanks as always

**Comment by EQuimper** [comment]
yes gonna make a video about it, thank for the idea didn't think of it

**Comment by kaiyes** [comment]
I think using redux will be simpler. https://github.com/react-community/react-navigation/issues/766

**Comment by baldurpan** [comment]
I managed to add a badge via tabBarIcon in navigationOptions. Works quite well in iOS but in Android it has some transparency (like opacity 0.7) unless the tab is focused. 
Very annoying.

**Comment by kaiyes** [comment]
@baldurpan  me too. I was able to add a badge as well. But I wasn't able to add subscription to that badge icon.

**Comment by EQuimper** [comment]
I think if you need to put that in subscriptions you gonna need to have it as his own component or wrote your own tabbar component. With React-Navigation thats pretty easy. I check this thing tonight maybe I can find something

**Comment by kaiyes** [comment]
This is what I have right now. But its static. 

![screenshot 2017-09-27 12 55 21](https://user-images.githubusercontent.com/5293742/30899767-223ccb3e-a383-11e7-9b8a-8179db4f6521.png)

**Comment by EQuimper** [comment]
Did you connect the tab for ? I mean this thing can be extends as a component I did on one of my app, and I think you can plug a subscriptions on this on

**Comment by kaiyes** [comment]
Will try that today.

**Comment by kaiyes** [comment]
One way to get out of this is to force the component to `refetch()` data upon render. So basically force the component to re-render. But it is a difficult task with react native.

**Comment by kaiyes** [comment]
tried another method. Made a notifications collection and fed notification query and subscription to icon component. However, the icon component doesn't take the subscription. Same subscription works in a normal page. I think the subscriptions won't work inside react-navigations. @EQuimper  what do you think ?

**Comment by kaiyes** [comment]
Finally was able to make the badge count reactive from the get-go. Answer lies in https://github.com/EQuimper/twitter-clone-with-graphql-reactnative/issues/39
