### ISSUE TITLE
app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#30]
Why can I have this error in the Part 0 ?
My code [now](https://github.com/gHashTag/twitter)

![2017-09-15 19 46 25](https://user-images.githubusercontent.com/6774813/30493923-c76d7d8a-9a4e-11e7-8092-5239428d936a.png)

**Comment by EQuimper** [comment]
@gHashTag you must have mongo db running on a other terminal :) Sorry to didn't say in the video

**Comment by gHashTag** [comment]
I apologize, maybe I do not understand something, but I'm launching a command in one terminal. Where am I wrong?
![bug mov](https://user-images.githubusercontent.com/6774813/30497877-2a7b24a0-9a5d-11e7-93a5-279e63bb3871.gif)

**Comment by EQuimper** [comment]
Can you run `mongod` on an other terminal. You need to start mongodb server.

**Comment by gHashTag** [comment]
Got it. Two terminals.
First `mongod`
![2017-09-15 22 19 27](https://user-images.githubusercontent.com/6774813/30499667-20665fb4-9a64-11e7-9cee-e659b02a1bd7.png)
and AFTER second `yarn dev`
![2017-09-15 22 19 37](https://user-images.githubusercontent.com/6774813/30499697-34857606-9a64-11e7-99f8-a2dad44af98f.png)

Thanks! Good job

**Comment by EQuimper** [comment]
yes :) sorry I didn't say in the video :s
