### ISSUE TITLE
--trailing-comma

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#31]
Personally for me it is redundant to use trailing comma, but why does not the hide trailing comma?
`--trailing-comma none`
What's wrong?

**Comment by EQuimper** [comment]
I love trailing-coma, I start to use it a lot in Golang and love it too in JS, make less bug when you want to add data and forget to put the comma on the first index. But this is pref :s

**Comment by gHashTag** [comment]
Thanks
