### ISSUE TITLE
Why don't work http://localhost:3000/

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#32]
![2017-09-16 16 37 05](https://user-images.githubusercontent.com/6774813/30512676-52081708-9afd-11e7-9812-2ed8cb1392d2.png)

**Comment by gHashTag** [comment]
mongod working:
![2017-09-16 16 37 40](https://user-images.githubusercontent.com/6774813/30512684-68cb3b82-9afd-11e7-81a9-c41a60f8aca7.png)

yarn dev working:
![2017-09-16 16 37 51](https://user-images.githubusercontent.com/6774813/30512693-87df856e-9afd-11e7-9a1b-d492e4d32021.png)

**Comment by gHashTag** [comment]
Now my [code](https://github.com/gHashTag/twitter)

**Comment by gHashTag** [comment]
Sorry http://localhost:3000/graphiql working =)

**Comment by EQuimper** [comment]
Yes this is not anymore like a rest api here, only one endpoint work :) but would be good to put a 404 page there or something likea a documention page I think

**Comment by gHashTag** [comment]
Thanks, I switched to Part 3
