### ISSUE TITLE
Part 9 bug report

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#33]
Have a nice day Emanuel!

Why can I have this error?
At the moment, my code is [here](https://github.com/gHashTag/twitter/tree/part9)
![simulator screen shot 18 2017 17 25 41](https://user-images.githubusercontent.com/6774813/30547016-e17d3c98-9c96-11e7-9762-df39b7301837.png)
![2017-09-18 17 29 37](https://user-images.githubusercontent.com/6774813/30547075-01d5eae4-9c97-11e7-8376-0a5cb479d180.png)
![2017-09-18 17 29 47](https://user-images.githubusercontent.com/6774813/30547079-03a22658-9c97-11e7-96b7-79b05fc295d1.png)

**Comment by gHashTag** [comment]
Change 
` uri: 'http://localhost:3000/graphiql'`
on
` uri: 'http://localhost:3000/graphql'`
...and working

**Comment by EQuimper** [comment]
:) Perfect you get it :) How you find the tutorial for now ?

**Comment by gHashTag** [comment]
All combined all the most recent and necessary technology. Better than the course did not even meet Udemy. I recommend your course to beginners in Russia!
Thank you, this is a great job!
