### ISSUE TITLE
(0 , _subscriptionsTransportWs.addGraphQLSubscriptions) is not a function

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#35]
It's me again Emanuel =)
Why do I have this error?
At the moment, my [code](https://github.com/gHashTag/twitter/tree/part15)

![2017-09-20 17 52 30](https://user-images.githubusercontent.com/6774813/30651075-4e85455a-9e2d-11e7-89ca-97a74d02f17a.png)
![simulator screen shot 20 2017 17 49 19](https://user-images.githubusercontent.com/6774813/30651077-517fdf22-9e2d-11e7-939d-0a5b93ac433d.png)

**Comment by EQuimper** [comment]
can I see your code what is your repo ? :)

**Comment by gHashTag** [comment]
This :)
![2017-09-20 23 23 13](https://user-images.githubusercontent.com/6774813/30665806-f12d5784-9e5a-11e7-9dfd-3d38efcbf63a.png)

**Comment by EQuimper** [comment]
Ok look like you dont save package in your packages.json https://github.com/gHashTag/twitter/blob/part15/mobile/src/package.json so hard to tell but did you install subscriptions-transport-ws ? `npm i -S subscriptions-transport-ws`

**Comment by gHashTag** [comment]
I cleaned the code, but now I see this error:
[My code here](https://github.com/gHashTag/twitter)
![simulator screen shot 21 2017 0 49 33](https://user-images.githubusercontent.com/6774813/30669422-f0256b04-9e66-11e7-92fd-067eb9ecdd80.png)

**Comment by gHashTag** [comment]
in version 0.9.0 stopped using addGraphQLSubscriptions
https://github.com/apollographql/subscriptions-transport-ws/issues/275
made a rollback to 0.8.2 and earned
Thank you

**Comment by chandlervdw** [comment]
`react-apollo@0.8.3` is the last version that includes `addGraphQLSubscriptions`
