### ISSUE TITLE
Hashes don't match when extracting file

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#36]
Why?
`error https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz: Hashes don't match when extracting file "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz". Expected "c40efc2357b70eeaecb3fa97a1874298155b7921" but got "9431e9c97eccd6aeb7f16b2929d1cc802ec74f87"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
![2017-09-21 19 09 01](https://user-images.githubusercontent.com/6774813/30706202-605a93a6-9f00-11e7-93bb-c2c8ab25f0e0.png)

**Comment by karsens** [comment]
rm -rf node_modules
watchman watch-del-all
rm -rf $TMPDIR/react-*
upgrade yarn
rm -rf yarn.lock
yarn

this fixed it for me, I think it's just the yarn.lock file though
