### ISSUE TITLE
Unhandled Promise Rejection (id: 0):

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#37]
What to do in such situations, I stand still because of this second week on stay part 15 (((
What? I do not understand?
Was entangled in authorization
My code [now](https://github.com/gHashTag/twitter)

![auuth mov](https://user-images.githubusercontent.com/6774813/31028504-e4d8d83e-a556-11e7-8058-76ba847df0ac.gif)
![simulator screen shot - iphone x - 2017-09-29 at 20 38 31](https://user-images.githubusercontent.com/6774813/31028507-e8498130-a556-11e7-9070-30d06c21b02d.png)
![simulator screen shot - iphone x - 2017-09-29 at 20 39 24](https://user-images.githubusercontent.com/6774813/31028509-eb1f584e-a556-11e7-8f8a-adb95d3a5543.png)

**Comment by gHashTag** [comment]
Need to reset AsyncStorage
```
componentWillMount() {
    AsyncStorage.removeItem("@twitteryoutubeclone") 
    this._checkIfToken()
 }
```

**Comment by EQuimper** [comment]
@gHashTag o yes the token must been bad, I'm doing a video tomorrow about the logout :)

**Comment by gHashTag** [comment]
Cool course! Thank you so much
