### ISSUE TITLE
Can't find field isFavorited on object 

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#38]
why do I have an error when the tweet is added?
![bug mov](https://user-images.githubusercontent.com/6774813/31047984-4d7e5618-a61d-11e7-9c45-fdfabab09939.gif)

![2017-09-30 20 20 32](https://user-images.githubusercontent.com/6774813/31047983-47b66446-a61d-11e7-8c9d-604ec4c7d8c1.png)

![simulator screen shot - iphone x - 2017-09-30 at 20 24 40](https://user-images.githubusercontent.com/6774813/31047991-6667e63a-a61d-11e7-9c01-25ddf9852f17.png)

**Comment by EQuimper** [comment]
I fix it in part 22 :) sorry about it :) https://youtu.be/3xt9Rm31Prc
