### ISSUE TITLE
Error when trying to add '@appandflow/touchable' package

### ISSUE THREAD

**Issue by MohammedBm** [EQuimper/twitter-clone-with-graphql-reactnative#45]
I get an error when i try to add this npm package using the following command `yarn add @appandflow/touchable` 

I get this error

```shell
error https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz: Fetch succeeded for undefined. However, extracting "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz" resulted in hash "9431e9c97eccd6aeb7f16b2929d1cc802ec74f87", which did not match the requested hash "c40efc2357b70eeaecb3fa97a1874298155b7921".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by EQuimper** [comment]
Umh, I just did in one of mu project an all was good, 
<img width="954" alt="screen shot 2017-11-24 at 10 30 05 am" src="https://user-images.githubusercontent.com/15819498/33216601-7a3a3950-d102-11e7-839d-57f08bc9cc81.png">

Maybe delete yarn.lock and node_modules and retry ?

**Comment by MohammedBm** [comment]
Its working perfectly, i guess it was the yarn.lock or the node_modules. By the way amazing work on the video. Love them!

**Comment by EQuimper** [comment]
@MohammedBm thank you :) I really appreciate it
