### ISSUE TITLE
Custom rules in your eslintconfig

### ISSUE THREAD

**Issue by gHashTag** [EQuimper/twitter-clone-with-graphql-reactnative#46]
How to exclude for example this error from the rules of your eslintconfig?

![2017-11-25 17 51 21](https://user-images.githubusercontent.com/6774813/33231619-4bfb41a8-d209-11e7-89d4-f0d275eafb8b.png)

**Comment by EQuimper** [comment]
In .eslintrc you can a rules object where you put

```
'Error/arrow-body-style': 0
```
